name: Deploy Range Config
on:
  push:
    paths:
      - 'config/ludus/ludus-range-config.yml'
  workflow_dispatch:

jobs:
  deploy_range:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard

      - name: Write WireGuard Config
        shell: bash
        env:
          WIREGUARD_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}
        run: echo "$WIREGUARD_CONFIG" | base64 --decode > wg0.conf

      - name: Activate WireGuard VPN
        run: sudo wg-quick up ./wg0.conf

      - name: Install Ludus CLI non-interactively
        run: |
          if ! command -v script >/dev/null; then
            echo "Error: script command not found. Aborting."
            exit 1
          fi
          script -q -c 'printf "y\ny\ny\n" | curl -s https://ludus.cloud/install | bash' /dev/null

      - name: Confirm Ludus API key is set
        run: |
          if [ -z "$LUDUS_API_KEY" ]; then
            echo "LUDUS_API_KEY is empty!"
            exit 1
          else
            echo "LUDUS_API_KEY is set."
          fi
        env:
          LUDUS_API_KEY: ${{ secrets.LUDUS_API_KEY }}

      - name: Deploy Ludus Range
        env:
          LUDUS_API_KEY: ${{ secrets.LUDUS_API_KEY }}
        run: |
          ludus range config set -f ./config/ludus/ludus-range-config.yml
          ludus range deploy

      - name: Disconnect WireGuard
        if: always()
        run: sudo wg-quick down ./wg0.conf
